// linkedin-draft.js
// Usage: node linkedin-draft.js path/to/post.md
//    or: node linkedin-draft.js --text "Your post content here"
//
// Runs headless on Mac. Auth session read from auth.json next to this script
// (generated by auth-export.sh), or from ~/.linkedin-playwright-state/auth.json.

// Set PLAYWRIGHT_BROWSERS_PATH BEFORE requiring playwright —
// Playwright reads this env var at module-init time, not at launch() time.
// Only override on Linux (Claude sandbox); on macOS use the system browser cache.
const path = require('path');
const os = require('os');
if (os.platform() === 'linux') {
  process.env.PLAYWRIGHT_BROWSERS_PATH = path.join(__dirname, '.playwright-browsers');
}

const { chromium } = require('playwright');
const fs = require('fs');

// Auth session resolution order:
//   1. Workspace-local auth.json (next to this script)
//   2. Legacy Mac home-directory path
const WORKSPACE_STATE = path.join(__dirname, 'auth.json');
const HOME_STATE = path.join(
  process.env.HOME || process.env.USERPROFILE || '',
  '.linkedin-playwright-state',
  'auth.json'
);
const STATE_PATH = fs.existsSync(WORKSPACE_STATE) ? WORKSPACE_STATE : HOME_STATE;

async function getPostContent() {
  const args = process.argv.slice(2);
  if (args[0] === '--text') {
    return args.slice(1).join(' ');
  }
  if (args[0]) {
    const raw = fs.readFileSync(args[0], 'utf8');
    // Strip YAML frontmatter: everything up to and including the second --- line
    const parts = raw.split(/^---\s*$/m);
    // parts[0] = "" (before first ---), parts[1] = frontmatter, parts[2+] = body
    const body = parts.length >= 3 ? parts.slice(2).join('---').trim() : raw.trim();
    return body;
  }
  throw new Error('Usage: node linkedin-draft.js path/to/post.md\n   or: node linkedin-draft.js --text "content"');
}

async function ensureLoggedIn() {
  if (fs.existsSync(STATE_PATH)) {
    console.log(`Using session: ${STATE_PATH}`);
    return;
  }
  throw new Error(
    '\n❌ No LinkedIn session found.\n' +
    '   Run auth-export.sh on your Mac to export your session:\n' +
    '     bash "ieppal-brand/linkedin posts/scripts/auth-export.sh"\n' +
    '   Then re-run this script.\n'
  );
}

// Try a list of locator strategies in order; return the first one that is visible.
async function findFirst(page, locators, timeout = 8000) {
  const deadline = Date.now() + timeout;
  while (Date.now() < deadline) {
    for (const loc of locators) {
      try {
        if (await loc.isVisible()) return loc;
      } catch { /* keep trying */ }
    }
    await page.waitForTimeout(300);
  }
  return null;
}

async function saveDraft(content) {
  await ensureLoggedIn();

  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ storageState: STATE_PATH });
  const page = await context.newPage();

  // ── 1. Load feed ──────────────────────────────────────────────────────────
  console.log('Navigating to LinkedIn feed...');
  await page.goto('https://www.linkedin.com/feed/', { waitUntil: 'domcontentloaded' });
  await page.waitForTimeout(3000);

  // ── 2. Open the post composer ─────────────────────────────────────────────
  // LinkedIn rotates CSS class names regularly. Use semantic / text selectors first.
  console.log('Opening post composer...');
  const triggerCandidates = [
    // Semantic (most stable — survives UI redesigns)
    page.getByRole('button', { name: /start a post/i }),
    page.getByText('Start a post, try a photo or video', { exact: false }),
    page.getByText('Start a post', { exact: true }),
    page.getByPlaceholder(/start a post/i),
    // Structural fallbacks (less stable but cover older/alternate layouts)
    page.locator('[data-control-name="share.sharebox_text"]'),
    page.locator('.share-box-feed-entry__trigger'),
    page.locator('.share-creation-state__placeholder'),
    page.locator('[aria-label*="Start a post" i]'),
    page.locator('[data-placeholder*="post" i]'),
  ];

  const trigger = await findFirst(page, triggerCandidates, 15000);
  if (!trigger) {
    // Last-resort: dump clickable text near the top of the feed for debugging
    const preview = await page.evaluate(() =>
      [...document.querySelectorAll('button, [role="button"], [tabindex="0"]')]
        .slice(0, 20)
        .map(el => `[${el.tagName}] aria="${el.getAttribute('aria-label')}" text="${el.innerText?.slice(0, 60)}"`)
        .join('\n')
    );
    await browser.close();
    throw new Error(
      '❌ Could not find the post composer trigger.\n' +
      '   LinkedIn may have updated their UI. Clickable elements found:\n' + preview + '\n\n' +
      '   Update triggerCandidates in linkedin-draft.js to match one of the above.'
    );
  }
  await trigger.click();
  await page.waitForTimeout(2000);

  // ── 3. Find the editor ────────────────────────────────────────────────────
  console.log('Pasting post content...');
  const editorCandidates = [
    // Semantic (most stable)
    page.getByRole('textbox', { name: /text editor/i }),
    page.getByRole('textbox').first(),
    // Structural fallbacks
    page.locator('.ql-editor[contenteditable="true"]'),
    page.locator('[contenteditable="true"]').first(),
    page.locator('[role="textbox"]').first(),
    page.locator('[data-placeholder]').first(),
  ];

  const editor = await findFirst(page, editorCandidates, 10000);
  if (!editor) {
    await browser.close();
    throw new Error('❌ Post composer opened but editor area not found. Check LinkedIn UI.');
  }
  await editor.click();
  await editor.pressSequentially(content, { delay: 10 });
  await page.waitForTimeout(1000);

  // ── 4. Trigger Save Draft dialog (Escape closes the modal) ────────────────
  console.log('Closing composer to trigger Save Draft dialog...');
  await page.keyboard.press('Escape');
  await page.waitForTimeout(2000);

  // ── 5. Confirm save ───────────────────────────────────────────────────────
  const saveCandidates = [
    page.getByRole('button', { name: /^save$/i }),
    page.getByRole('button', { name: /save draft/i }),
    page.locator('[data-control-name="discard_share_save"]'),
    page.locator('button:has-text("Save")').first(),
  ];

  const saveBtn = await findFirst(page, saveCandidates, 5000);
  if (saveBtn) {
    await saveBtn.click();
    console.log('✅ Draft saved to LinkedIn.\n');
  } else {
    // Fallback: modal might show a Dismiss/Close button first
    const dismissCandidates = [
      page.getByRole('button', { name: /dismiss/i }),
      page.getByRole('button', { name: /close/i }),
      page.locator('[aria-label="Dismiss"]'),
    ];
    const dismiss = await findFirst(page, dismissCandidates, 3000);
    if (dismiss) {
      await dismiss.click();
      await page.waitForTimeout(1000);
      const retry = await findFirst(page, saveCandidates, 3000);
      if (retry) {
        await retry.click();
        console.log('✅ Draft saved (fallback path).\n');
      } else {
        console.log('⚠️  Could not confirm save — check LinkedIn drafts manually.');
      }
    } else {
      console.log('⚠️  Save dialog not detected — check LinkedIn drafts manually.');
    }
  }

  await page.waitForTimeout(2000);
  await context.close();
  await browser.close();
}

getPostContent()
  .then(saveDraft)
  .catch(err => {
    console.error('Error:', err.message);
    process.exit(1);
  });
